version: "3"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5433:5433
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGPORT: 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - .data/neo4j:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: neo4j/1234
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1024m
      NEO4J_dbms_memory_pagecache_size: 1024m
    healthcheck:
      test: ["CMD-SHELL", "neo4j status | grep running"]
      interval: 10s
      timeout: 5s
      retries: 10



  subquery-node:
    image: onfinality/subql-node:v0.27.2
    depends_on:
      "postgres":
        condition: service_healthy
      "neo4j":
        condition: service_healthy
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      DB_ENABLE: 1
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASS: postgres
      NEO4J_ENABLE: 1
      NEO4J_HOST: bolt://neo4j
      NEO4J_USER: neo4j
      NEO4J_PASS: 1234
      ES_ENABLE: 1
      ES_HOST: http://es:9200
      ES_USER: elastic
      ES_PASS: abcd
      EMAIL_ALERT_ENABLE: 0
      EMAIL_ALERT_HOST: host
      EMAIL_ALERT_FROM: from
      EMAIL_ALERT_TO: to
      EMAIL_ALERT_KEY: api_key
    volumes:
      - ./:/app
      - ./sandbox.override.js:/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.service.js
    command:
      - -f=/app
      - --db-schema=app
      - --log-level=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:v0.11.0
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5433
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - logger.level=WARN
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=abcd
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_URL=http://es:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=abcd
