version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5433:5433
    volumes:
      - .data/postgres:/var/wika_etl/postgres_data
    environment:
      POSTGRES_PASSWORD: postgres
      PGPORT: 5433

  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5433
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --local

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      - "postgres"
      - "subquery-node"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5433
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000
