specVersion: 0.2.0
name: subql_wika
version: 1.0.0
description: ''
repository: https://github.com/randombishop/wika_etl
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x59732b25bb635769e91a71f818c6d845b9bdcd371bb93d1512b1eacedb53d4be'
  endpoint: wss://testnode3.wika.network:443
dataSources:
  - kind: substrate/Runtime
    startBlock: 1597501
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
